import { Icon } from "@mui/material";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Layout } from "~/components/modules";

import { api } from "~/utils/api";

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Vange Web</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/vwulog.ico" />
      </Head>
      <main className="flex min-h-screen flex-col ">
        <div className="flex min-h-screen flex-col md:flex-row">
          <div className="flex-colf shadow-right-md z-10 flex  md:w-[500px] ">
            <div className="logo p-2 ">
              <div className="flex flex-row items-center gap-5">
                <Image alt="logo" src="/logo.png" width={64} height={64} />
                <span className="font-mono text-xl">Vangen Webutvikling</span>
              </div>
            </div>
          </div>
          <div className="flex flex-1 bg-blue-300"></div>
        </div>
      </main>
    </>
  );
}

function AuthShowcase() {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = api.example.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined },
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={
          sessionData ? () => void signOut() : () => void signIn("auth0")
        }
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
}
